### ISSUE TITLE
System.OverFlowException en ReadInt()

### ISSUE THREAD

**Issue by X509Whatever** [pikachumm/CalculatorService#12]
Mientras Jenkins me buildea la rama, voy a intentar romper tu código xd

> Tu función ReadInt() tiene un pequeño problema, y es que en el try catch que usas para leer un número solo estás mirando System.FormatException, por lo que, al introducir un número que int no puede almacenar, peta, y ahí se queda xd

![image](https://user-images.githubusercontent.com/49149147/95518978-7e2c3b00-09c4-11eb-8c76-79f871da4239.png)
![image](https://user-images.githubusercontent.com/49149147/95519329-2b9f4e80-09c5-11eb-8ae0-94bcfa962cc8.png)

> El arreglo más sencillo que le veo a esto es quitar catch (System.FormatException) y poner catch (Exception).
> Y la calculadora seguirá funcionando xd (o le añades un catch más que sea para esta excepción, pero si miras por Exception va rodao xdd)

![image](https://user-images.githubusercontent.com/49149147/95519511-85077d80-09c5-11eb-9d53-cc54ceced75a.png)

**Comment by atthepit** [comment]
Generalmente no es buena idea hacer `catch(Exception)` porque puede hacer que te comas algunos errores importantes sin darte cuenta.

No pasa nada por añadir un nuevo catch más abajo con la _OverFlowException_ y tratarla aparte.

**Comment by X509Whatever** [comment]
> Generalmente no es buena idea hacer `catch(Exception)` porque puede hacer que te comas algunos errores importantes sin darte cuenta.
> 
> No pasa nada por añadir un nuevo catch más abajo con la _OverFlowException_ y tratarla aparte.

Toda la razón, pero como comento, es la solución "sencilla" xd

Por ejemplo, **donde sí que no veo correcto el uso de Exception es en la parte servidor en los controladores, donde se hace un catch (Exception) y un throw Exception() sin pintar un stacktrace ni nada (acorde a la causa que lo genera)**... (como cuando intentas dividir entre 0; quizás un _DivideByZeroException_ quedaría kool

_Al final, la calculadora se la complica cada uno como quiere (:_
